baseURL = 'https://bitpaus7.github.io/'
languageCode = 'en-us'
title = 'bit'
theme = 'pehtheme-hugo'

[params]
  siteName = "BITPAUS"
  description = 'Alam0x adalah platform Informasi seputar crypto, dengan visi membangun literasi digital dan finansial yang kuat bagi seluruh masyarakat Indonesia, Serta meningkatkan kesadaran akan bahaya nya judi online.'
  mainSections = 'posts'

  [params.author]
    name = "X"
    bio = "Penulis artikel blog tentang teknologi dan investasi crypto."


[pagination]
  pagerSize = 9 # Set the desired number of posts per page
  summaryLength = '20' # <- 20 words are approximately 160 characters
  googleAnalytics = 'G-B54LJHB6HR' # <- Your GA-4
  disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[author]
  name = 'Anthony Arphan'
  bio = 'Debitis assumenda esse dignissimos aperiam delectus maxime tenetur repudiandae dolore'
  avatar = '/images/nasa-astronaut-unsplash.jpg'
  twitter = 'https://twitter.com/insertapps'
  

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'Berita'
    pageRef = '/tags/berita'
    weight = 15
  [[menu.main]]
    name = 'Airdrop'
    pageRef = '/tags/airdrop'
    weight = 20
  [[menu.main]]
    name = 'Tutorial'
    pageRef = '/tags/tutorial'
    weight = 25
  [[menu.main]]
    name = 'Opini'
    pageRef = '/tags/opini'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

  [[module.mounts]]
    source = 'assets'
    target = 'static'

[permalinks]
  posts = "/:slug/"
  halaman = "/:slug/"
  tags = "/:slug/"
